MINDBRICKS ICE STACK release 0.55 to Global Edge Software Ltd.
MINDBRICKS ICE STACK release 0.55 to Global Edge Software Ltd. This
incremental release contains fixes for 5 issues reported by Global Edge
Software Ltd against previous release 0.54.

Still planning for the final release to Global Edge. If in case we do
not get any further issues, then we can think of giving the final
version. However, if they continue testing various scenarios then it
would make our ICE stack robust and well tested.

Pasted below are the 5 issues that were reported by Global Edge Software
Ltd against rel 0.54. Some are non-issues like -  issue 1 which is
related to libc version of the platform and issue2 which is related to
trivial changes related to the reference platform layer.

-------------------------------------------------------------------------------

1. Compilation error (gcc version 4.1.2)- Initialization of 'static
rfc3484_addr_sel_rule_t def_policy_table' in
'ice_lite/src/ice_addr_sel.c'
    In FC8
[CC]  ice_addr_sel.c ...
ice_addr_sel.c:83: error: unknown field ‘__in6_u’ specified in
initializer
ice_addr_sel.c:83: error: unknown field ‘__u6_addr8’ specified in
initializer
    In ubuntu
[CC] ice_addr_sel.c ...
ice_addr_sel.c:83:9: error: unknown field ‘in6_u’ specified in
initializer
ice_addr_sel.c:83:9: error: unknown field ‘u6_addr8’ specified in
initializer

    Please find the diff file 'ice_54_diff' for the fix and review/test
the same.

2. Unwanted function in Platform for Application - In
platform/src/platform_api.c

After the integration some of the function and definitions which are
unused by the ICE stack
are moved under the Macro 'PLATFORM_USE_MISC_API'. It would be better
this
conditional compilation macro changes present in platform_api.c in order
to avoid redefinition while integration.

3. Call from FULL -to- LITE : Nomination not done for RTCP component
 - same as Bug reported on Nov 24, 2011 - Reproducing the same.

During call from ICE FULL agent to ICE LITE agent, Connectivity Check
with the USE-CANDIDATE attribute
(i.e Nomination) is NOT sent for RTCP component.

Setup:
ICE LITE Agent : Connected to public
IP addr - 172.16.8.62

ICE FULL Agent : Behind Router/NAT
Host IP addr - 192.168.1.11
Router/NAT addr (mapped addr) - 172.16.8.139

Nomination is NOT sent for RTCP component.

Attachments:
cc_rtcp_issue/ice_full2lite_caller.pcap : ICE -FULL agent capture
cc_rtcp_issue/ice_full2lite_callee.pcap  : ICE-LITE agent capture
cc_rtcp_issue/log_ice_full2lite_caller.txt  : ICE -FULL agent log
messages
cc_rtcp_issue/log_ice_full2lite_callee.txt  : ICE -LITE agent log
messages

4. Call from LITE -to- FULL Nomination not done for RTP component
During call from ICE LITE agent to ICE FULL agent, Connectivity Check
with the USE-CANDIDATE attribute
(i.e Nomination) is NOT sent for RTP component.

Setup:
ICE LITE Agent : Connected to public
IP addr - 172.16.8.62

ICE FULL Agent : Behind Router/NAT
Host IP addr - 192.168.1.11
Router/NAT addr (mapped addr) - 172.16.8.139

Attachments:
cc_rtp_issue/ice_lite2full_callee.pcap : ICE -FULL agent capture
cc_rtp_issue/ice_lite2full_caller.pcap : ICE-LITE agent capture
cc_rtp_issue/log_ice_lite2full_callee.txt : ICE-FULL agent log messages
cc_rtp_issue/log_ice_lite2full_caller.txt: ICE-LITE agent log messages

5. Call from FULL -to- FULL - ICE session NOT moving to completed state
During call from ICE FULL agent to ICE FULL agent, caller ICE session
state completed and intimated to application.
But callee side ICE session is not moved to completed state.

Setup:
ICE FULL Agent Caller
Host IP addr - 192.168.1.11
Router/NAT addr (mapped addr) - 172.16.8.139

ICE FULL Agent Callee
Host IP addr - 192.168.0.89
Router/NAT addr (mapped addr) - 172.16.8.89

Attachments:
full2full_sess_comp_issue/full2full_callee_without_rtcp.pcap
full2full_sess_comp_issue/full2full_caller_without_rtcp.pcap
full2full_sess_comp_issue/log_full2full_callee_without_rtcp.txt
full2full_sess_comp_issue/log_full2full_caller_without_rtcp.txt

-------------------------------------------------------------------------------