Integrated changes suggested by Global Edge for rel 0.54 - issues #1 & #2
Integrated code changes suggested by Global Edge Software for ICE STACK
release ver 0.54. The changes are all trivial code changes, such as log
statements and libc related change.

Pasted below is the mail excerpt provided by Global Edge for Issues #1
and #2.

--------------------------------------------------------------------------------

1. Compilation error (gcc version 4.1.2)- Initialization of 'static
rfc3484_addr_sel_rule_t def_policy_table' in
'ice_lite/src/ice_addr_sel.c'
    In FC8
[CC]  ice_addr_sel.c ...
ice_addr_sel.c:83: error: unknown field ‘__in6_u’ specified in
initializer
ice_addr_sel.c:83: error: unknown field ‘__u6_addr8’ specified in
initializer
    In ubuntu
[CC] ice_addr_sel.c ...
ice_addr_sel.c:83:9: error: unknown field ‘in6_u’ specified in
initializer
ice_addr_sel.c:83:9: error: unknown field ‘u6_addr8’ specified in
initializer

    Please find the diff file 'ice_54_diff' for the fix and review/test
the same.

2. Unwanted function in Platform for Application - In
platform/src/platform_api.c

After the integration some of the function and definitions which are
unused by the ICE stack
are moved under the Macro 'PLATFORM_USE_MISC_API'. It would be better
this
conditional compilation macro changes present in platform_api.c in order
to avoid redefinition while integration.

--------------------------------------------------------------------------------